# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:
    inputs:
      group_name: 
        description: 'group name'
        required: true
        default: Warning    

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # - uses: azure/login@v2
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}
    #     allow-no-subscriptions: true

    # - name: Azure CLI script
    #   uses: azure/cli@v2
    #   with:
    #     azcliversion: latest
    #     inlineScript: |
    #       az login
    #       az ad group create --display-name ${{ github.event.inputs.group_name }} --mail-nickname ${{ github.event.inputs.group_name }}

    - name: print the runtime parameter
      run: echo "The input is ${{ github.event.inputs.group_name }}"

    - name: run shell scripts
      run: |
            echo ${{GITHUB_WORKSPACE}}
            ${{GITHUB_WORKSPACE}}/printdate.sh
      
