# File: .github/workflows/workflow.yml

on: 
  workflow_dispatch:
    inputs:
      loglevel: 
        description: 'Log level'
        required: true
        default: Warning
      tags:
        description: "Test Scenario tags"
    

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az resource list
